#page title
page_title                                :            Whatsleft?
# Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120
# Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us
# Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
appstore_link                             :                                           #Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : TODO.
 # Enter Google Play Store URL.
presskit_download_link                    : todo.
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Whatsleft?
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An app to help you manage your daily tasks, meal plans and routines.

enable_smart_app_banner                   : true
# Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Rohit Agarwal
your_link                                 :
your_city                                 : Munich
email_address                             : rohit.agarwal2014@gmail.com
linkedin_username                         : rohit-agarwal-01740380
linkedin_company                          :
facebook_username                         :
instagram_username                        :
twitter_username                          : r0hit0303
github_username                           : r0hit0303
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Generate and share thousands of recipes.
    description                           : Manage your recipes, create meal plans, and share them with friends and family.
    fontawesome_icon_name                 : magic

  - title                                 : Create meal plans and assign tasks.
    description                           : Plan your meals for the week, including breakfast, lunch, and dinner and assign tasks to family members.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Share responsibility for a dependant with a group member.
    description                           : Create routines for your dependant. A dependant can be your kids, parents, plants and even pets!
    fontawesome_icon_name                 : user-friends

  - title                                 : Create, manage and generate tasks.
    description                           : Clean and minimalistic UI so you can focus on what matters most. Create, manage, generate, assign and so much more!
    fontawesome_icon_name                 : tasks

  - title                                 : Groups
    description                           : Groups help to share tasks, meal plans and routines with other members.
    fontawesome_icon_name                 : users

  - title                                 : Light/dark mode
    description                           : Switch between light and dark mode with a single tap or automatically based on your system settings.
    fontawesome_icon_name                 : moon

# Theme Settings
topbar_color                              : "#9299f7"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

canonical_url                             : https://whats-left.de
og_image                                  : https://whats-left.de/assets/social-media-banner.png

# Markdown rendering
markdown: kramdown
